### ISSUE TITLE
pdflatex main.tex fails with "kodi.sty not found"

### ISSUE THREAD

**Issue by edrx** [paolobrasolin/kodi#21]
If I run

    cd doc/ && pdflatex main.tex

it fails with a:

    ! LaTeX Error: File `kodi.sty' not found.

Here's how to reproduce the error (btw, I'm on Debian):

    rm -Rfv ~/usrc/kodi/
    cd      ~/usrc/
    git clone https://github.com/paolobrasolin/kodi
    cd      ~/usrc/kodi/
    # git reset
    cd      ~/usrc/kodi/doc/
    pdflatex main.tex

**Comment by paolobrasolin** [comment]
Hi @edrx. Thanks for reporting the error!

The gist of the issue is: it used to be tricky to compile the manual without installing koDi first because it contains some live examples.

I recently made the switch from `rake` to `make` for the build system (https://github.com/paolobrasolin/kodi/issues/24) and it is now straightforward to get going.

🚀To build everything and install it in your local tree:

```bash
git clone https://github.com/paolobrasolin/kodi
cd kodi
make install
```

Once you do that,`kodi` will be available to `\usepackage` just like any other package.
You'll also find the compiled manual (which you were trying to obtain) at `./build/kodi-doc.pdf` in the repo.

😿To get rid of koDi:

```bash
# (clone and) cd into the repo as above, then
make uninstall
```

Please let me know whether this works out for you!
